version: '3'

services:
  # bdc-bdc_geoserver-geoserver:
  #   build: ./
  #   container_name: bdc-bdc_geoserver-geoserver
  #   environment:
  #     - bdc_geoserver_SERVICE_DATACUBE=http://127.0.0.1:5030
  #     - bdc_geoserver_SERVICE_LAMBDA_DATACUBE=http://127.0.0.1:5040
  #     - ENVIRONMENT=prod
  #     - KEYSYSTEM=Key#2019@BDC#hash
  #   volumes:
  #     - "./:/usr/src/app"
  #   working_dir: "/usr/src/app"
  #   ports:
  #     - "5015:5000"
  #   restart: always
  #   networks:
  #     - bdc

  bdc-geoserver:
    hostname: bdc-geoserver
    container_name: bdc-geoserver
    image: kartoza/geoserver
    environment:
      - GEOSERVER_ADMIN_PASSWORD=geoserver
    volumes:
      - ./geoserver_data:/opt/geoserver/data_dir
      - ./files:/home/data/files
    ports:
      - "8081:8080"
    networks:
      - bdc

networks:
  bdc:
    driver: bridge
