version: '3'

services:
  bdc-geoserver:
    build: ./
    container_name: bdc-geoserver
    environment:
      - URL_GEOSERVER=geoserver:8080
      - ENVIRONMENT=DevelopmentConfig
      - KEYSYSTEM=Key#2019@Geoserver#hash
      - PATH_BASE_GEOSERVER=file:///home/data/cubes
      - PATH_CUBES_FILE=/home/bdc/files,
      - POSTGRES_DATABASE=bdc,
      - POSTGRES_USER=postgres,
      - POSTGRES_PASSWORD=postgres,
      - POSTGRES_HOST=127.0.0.1,
      - POSTGRES_PORT=5433
    volumes:
      - "./:/usr/src/app"
    working_dir: "/usr/src/app"
    ports:
      - "5000:5000"
    restart: always
    networks:
      - bdc_net_geoserver

  geoserver:
    hostname: geoserver
    container_name: geoserver
    image: kartoza/geoserver
    environment:
      - GEOSERVER_ADMIN_PASSWORD=geoserver
    volumes:
      - ./geoserver_data:/opt/geoserver/data_dir
      - ./files:/home/data/files
    ports:
      - "8081:8080"
    networks:
      - bdc_net_geoserver

  postgis:
    hostname: postgis
    container_name: postgis
    image: kartoza/postgis
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_DBNAME=bdc
    volumes:
      - postgres-data:/var/lib/postgresql
    ports:
      - "54321:5432"
    networks:
      - bdc_net_geoserver

networks:
  bdc_net_geoserver:
    driver: bridge

volumes:
  postgres-data: