version: '3'

services:
  bdc-geoserver:
    build: ./
    container_name: bdc-geoserver
    environment:
      - URL_GEOSERVER=geoserver:8080
      - ENVIRONMENT=DevelopmentConfig
      - KEYSYSTEM=Key#2019@Geoserver#hash
    volumes:
      - "./:/usr/src/app"
    working_dir: "/usr/src/app"
    ports:
      - "5015:5000"
    restart: always
    networks:
      - bdc_net_geoserver

  geoserver:
    hostname: geoserver
    container_name: geoserver
    image: kartoza/geoserver
    environment:
      - GEOSERVER_ADMIN_PASSWORD=geoserver
    volumes:
      - ./geoserver_data:/opt/geoserver/data_dir
      - ./files:/home/data/files
    ports:
      - "8081:8080"
    networks:
      - bdc_net_geoserver

networks:
  bdc_net_geoserver:
    driver: bridge
