openapi: 3.0.0

info:
  description: Web service to publish layers and cubes in Geoserver - Brazil Data Cube
  version: "1.0"
  title: API publish cubes in Geoserver
  contact:
    name: Brazil Data Cube
    email: example@example.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

tags:
  - name: "coverages"
    description: "Manager coverages (mosaicPyramid) in Geoserver"
  - name: "status"
    description: "Status services"
    
paths:
  /geoserver/status:
    get:
      tags:
        - "status"
      summary: "Status application"
      description: "return status of application"
      responses:
        200:
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  success:
                    type: boolean

  /geoserver/coverages/{workspace}:
    get:
      tags:
        - "coverages"
      summary: "List Cubes"
      description: "return list de cubes/layers published"
      parameters:
        - in: "path"
          name: "workspace"
          required: true
          description: "Name of Workspace"
      responses:
        200:
          description: Coverages Published
          content:
            application/json:
              schema:
                type: object
                properties:
                  coverageStore:
                    type: array
                    items:
                      $ref: "#/components/schemas/CoverageStore"
                  success:
                    type: boolean

  /geoserver/coverages/{workspace}/{coveragestore}/{coverage}:
    delete:
      tags:
        - "coverages"
      summary: "Unpublish"
      description: "Unpublish and remove cube/layer"
      parameters:
        - in: "path"
          name: "workspace"
          required: true
          description: "Name of Workspace"
        - in: "path"
          name: "coveragestore"
          required: true
          description: "Name of Coverage Store"
        - in: "path"
          name: "coverage"
          required: true
          description: "Name of Data Cube (coverage)"
      responses:
        200:
          description: Depublization status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseStatus"
  
  /geoserver/coverages/:
    post:
      tags:
        - "coverages"
      summary: "Publish"
      description: "Create coverage store and publish cube"
      requestBody:
        description: "Initial informations to publish datacube"
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CoverageRequest"
      responses:
        201:
          description: Publication status
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResponseStatus"


components:
  schemas:
    ResponseStatus:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
    
    CoverageStore:
      type: object
      properties:
        name:
          type: string
        href:
          type: string
          
    CoverageRequest:
      type: object
      properties:
        workspace: 
          type: string
          description: 'datacube'
        datastore:
          type: string
          description: 'brazilsentinel'
        layer:
          type: string
          description: 'brazil'
        path:
          type: string
          description: '/brazil'
        description:
          type: string
          description: 'brazil data cube with sentinel'
        projection:
          type: string
          description: 'EPSG:4326'